### ISSUE TITLE
Restructuring the citation system

### ISSUE THREAD

**Issue by runjak** [lingdb/CoBL#306]
This issue tries to coordinate the different parts that need to be handled in improving the current citation system.

A possible roadmap would be:
1. Starting with restructuring the table and its data as requested in #148.
   - This should give us the possibility to present sources in a more structured manner, which will make it possible to be compatible with Zotero and others later.
   - For this step it is important to keep a mapping from current source IDs to the new, more structured data so that adjusting the table layout can use this.
   - This step may need to disable current ways to enter citation data if they are incompatible with the new table layout.
2. When going through the current sources from the database @nitsnatsnok found some duplicate entries and others that should be removed. This should be cleaned up before the entries could change. The issue for this is #223.
3. Once the sources table is adjusted we need means on the page to edit them correctly and display them in a more structured manner. This is basically issues #95, #169.
   - For this step the question of how to best present sources, which is posed in #183 would need to be solved.
4. Make it possible to export `.bib` from sources and support Zotero (RDF) in the pages templates.
5. The source information that is currently kept in note fields can be put into a more structured format by @nitsnatsnok as mentioned in #258.

**Comment by runjak** [comment]
@PaulHeggarty, @cormacanderson - @nitsnatsnok made me aware that some of the current sources are expert names and the question arose whether these should be collapsed with our current Authors? Are Authors also (potential) sources, or should these be kept entirely separate?

**Comment by runjak** [comment]
When looking at the authors table it became apparent that some initials have conflicts (different authors with potentially the same initials.). This is currently solved in different ways. For example we have:
* `MM` and `MM2`
* `KS` and `KSc`

It would make sense to stick to one schema here, right?

**Comment by runjak** [comment]
The current source list displays counts for different places citations occur.
These places are:
1. A lexeme cites a source
2. A cognate class cites a source
3. A cognate judgement cites a source

- The third case currently isn't represented in the source list, which is presumably a bug?

**Comment by runjak** [comment]
Since it's related:
I'm not sure how the counts displayed for sources are computed.
It's entirely possible that they are just for the whole database, instead of considering a users current default lists or filtering for lexemes that have `not_swadesh_term=False`.

**Comment by khoidt** [comment]
I'm wondering if the following new fields of the Source model are to be represented via remote relations to different (new) models, namely:
-     author (M2M)
-     type (FK / Choices)
-     editor (M2M)
-     journal (FK)
-     school (FK)
-     address (FK)
-     series (FK)
-     publisher (FK)
Generally, I find it much more practical in such cases then using CharFields or TextFields.
@runjak @nitsnatsnok @PaulHeggarty, what would you say?

**Comment by runjak** [comment]
* I'm in favor of foreign keys here - type would be a candidate where a `CharField` might work - but the others would possibly make useful tables.
* I also think that there was some discussion about the authors/experts situation with @PaulHeggarty and @cormacanderson, but I can't quite remember what the decision on this was - some clarification would help with this, I guess.

**Comment by khoidt** [comment]
The `Source` model has now two new M2M fields (`author` and `editor`) relating to the existing `Author` model. I'd suggest to extend the `Author` model with an additional field ("type" or the like) for distinguishing between CoBL authors and source authors. What would you say? 

Alternatively, one could create a separate model for authors of sources, but it seems like a multiplication of entities.

**Comment by runjak** [comment]
I think a type distinction sounds like the clever thing to do in this case - given that the tables are otherwise similar.

**Comment by PaulHeggarty** [comment]
We're storing initials, by the way, as the filenames of the corresponding image files for the author photos.

**Comment by PaulHeggarty** [comment]
Citations, by the way, should be based on the standard Harvard system, i.e. a unique combination of Author(s) (or Editor, if no author) plus year of publication.  Plus a disambiguation letter after the year, if necessary:  i.e. Smith 2001a, Smith 2001b.  
We need to keep the citation dropdown box, and the text shown on the screen, limited to this, of course.  Only on the (new) bibliography reference page should we have the full bibliography entries that correspond, embedded in some bibtex format so that things like Zotero can recognise the bibliography entries from the webpage. 
Not sure if all is clear here, we probably need to meet on this next week.

**Comment by khoidt** [comment]
I've changed the fields in the `Source` model to better match the data. Now only a couple of entries are not being updated (due to some other issues, still not very clear).

**Comment by nitsnatsnok** [comment]
According to the mail correspondence between Paul, Ilya and me I'm setting up a new list of tasks concerning the new bibliography system. They are roughly organised by importance and chronological order, feel free to edit and comment:

- [ ] “deprecated” radioboxes: make it clear what the radioboxes are for, make it possible to save changes (e.g. with a red “Save” button on the top like usual on the website) @khoidt
- [ ] author/editor: for entries without an author, output the editor(s) instead @khoidt
 - This poses a new problem: How do we integrate this in the desired sortable table without making it overly wide? Considering what I wrote on [issue 183](https://github.com/lingdb/CoBL/issues/183), maybe it would be of use to output just the short citation form (= author year[disambiguation letter]) without the ability to sort the list? @Paul, what do you think about this question?
- [ ] parser issues: output author's surnames first (citing Paul: “It is quite a common citation style that a first author of a paper is given as [Surname, Forename(s)] but any subsequent co-authors are given [Forename(s) Surname].)” @khoidt
- [ ] wiki page: write a detailed wiki page explaning the system @nitsnatsnok

**Comment by khoidt** [comment]
The 'deprecated' checkboxes look and function for now like this:
![deprecated](https://cloud.githubusercontent.com/assets/7487683/19729364/091d7120-9b97-11e6-9c31-1d2ff27b7606.jpg)
Is it clear enough what they are for and how they function? If not, how should it be improved?
Save: the `deprecated` field is saved now on the fly with JQuery `POST ` request when a checkbox is clicked. Do you think we need a special button for this? @nitsnatsnok @PaulHeggarty

**Comment by nitsnatsnok** [comment]
OK, thank you! I think it would be useful to add “deprecated” in the column head to make clear what the boxes are for, maybe turned by 90 degrees. Saving on the fly is OK for me, but for the sake of both consistency and usability I think it would be good to add a “Save” button. Others tasks are more important now though.

**Comment by khoidt** [comment]
Author/editor: 
I would use the same 'Author' column, with adding "(ed.)" after the name(s). E.g.
> Gvozdanović, Jadranka (ed.)

The short citation form (+ long citation form?) I would rather add as a row in 'Details'. Or do you think there should be a column for it?

Parser issues:
The BibTeX parser I'm using takes the data from `.bib` file "as is", so the author's surname and forename come exactly as in the same order as in the file, which is inconsistent. I probably could write a script to correct it or look for ready solutions (I suspect it also could be solved with the aid of the citation software used to edit the file). @nitsnatsnok @PaulHeggarty

**Comment by nitsnatsnok** [comment]
> The BibTeX parser I'm using takes the data from .bib file "as is"

This surprises and worries me a lot, as this will let a bunch of new issues arise: How to generate the short form with e.g. an abbreviated author's list correctly if the parser can't do this? For example:

file | short form | long form
---|---|---
Müller, A. and Meyer, A. and Schulze, A.|Meyer et al.|Meyer, A., A. Müller and A. Schulze

It's a core functionality of Bib(La)TeX to deal with such things, if we can't use this I honestly don't know how to reach our goal. Maybe we let Bib(La)TeX do the work and use it's output in any way? It would be necessary to run it every time we change a source or enter a new one, but this should not happen too often. Unfortunately I don't understand enough of the programming background to be of much use in this question.

**Comment by khoidt** [comment]
@nitsnatsnok, I went through the authors' names and corrected them manually. The changes are the following:

Felix Rau > Rau, Felix
Klein , E. > Klein, E.
Parmanand Mewaram > Mewaram, Parmanand
H. G. Liddell and R. Scott. and H. S. Jones > Liddell, H. G. and Scott, R. and Jones, H. S.
Helmut Rix > Rix, Helmut
Einar Haugen > Haugen, Einar
J. ten Doornkaat Koolman > ten Doornkaat Koolman, J.
Kur'janka M. > Kur'janka, M.
Zoze Murgoski > Murgoski, Zoze
Martin Joachim Kümmel >  Kümmel, Martin Joachim
Tijmen Pronk > Pronk, Tijmen
L. Ceplītis and others > Ceplītis, L. and others
Konstantin Stephan > Stephan, Konstantin
Novák Ľubomír > Novák, Ľubomír
Jacob Grimm and Wilhelm Grimm > Grimm, Jacob and Grimm, Wilhelm

Updated `.bib` data:
[lexicon_source.zip](https://github.com/lingdb/CoBL/files/554060/lexicon_source.zip)

Other possible error (not corrected):
{Tsabolov = Cabolov}, R. L.

**Comment by khoidt** [comment]
## Recent  updates
### Merge / delete / deprecate sources
See [my last comment](https://github.com/lingdb/CoBL/issues/223#issuecomment-256815113) in #223

### Update from uploaded BibTeX file
Now as button in `/sources/` or `/sources/import`. After `.bib` file(s) submitted, a table displays the newly added sources and the changes in the existing data. Confirmed by the "Update" button.

### Export to BibTeX file
Now as button in `/sources/` or `/sources/import`. Exports all the sources in the database to a single `.bib` file.

### Short citations and data
The Source model has now short citation (+ siglum). Here is the complete list for the data I have:
[short_citations.txt](https://github.com/lingdb/CoBL/files/557449/short_citations.txt)
It probably makes sense to check for incorrect data (appears at least the first few entries), @nitsnatsnok.

---
After a few tests tomorrow the branch will be ready for merging and deployment @runjak.

**Comment by nitsnatsnok** [comment]
# Short citations and data
As I expected, this yields a lot of errors: Things like “1930/1935” are meant to be “1930–1935”, „Michael Meier-Brügger 2000“ should be „Meier-Brügger 2000“ (regardless of whether the author field in the bib file says „Michael Meier-Brügger“ or „Meier-Brügger, Michael“) etc. pp.
It seems the only way to use the output [lexicon_source.pdf](https://github.com/lingdb/CoBL/files/558128/lexicon_source.pdf) – I'm still trying to get it to show a proper short form before every entry, but until then you can as well make “Adams, Douglas Q. (1999a)” to “Adams 1999a” using `sed` or the like. In lines without year (= experts, online sources etc.), just take everything before the first point.
To get this bibliography, I had to do some changes to the bib file, I'll upload the current version as soon as this is possible.

**Comment by khoidt** [comment]
@runjak I have merged the #306 branch with devel, so you can deploy it now.

**Comment by nitsnatsnok** [comment]
> I will make a list of such empty entries to see exactly what each of them represents. (quote from @khoidt in #333)
That's is a good idea, please also upload it here.

Did you use the short citation forms I posted [above](https://github.com/lingdb/CoBL/issues/306#issuecomment-256888567)?

**Comment by nitsnatsnok** [comment]
@khoidt: The sources list still doesn't show the correct short forms. If the parser can't convert things like “1959/1995” and “2016-06-30” just use the data from the biblatex output [above](https://github.com/lingdb/CoBL/issues/306#issuecomment-256888567) instead.
When will be the next deployment?

**Comment by khoidt** [comment]
I will be working on this tonight and tomorrow the whole day, so the new version should be ready soon (hopefully, tomorrow evening or on Saturday the latest). I will introduce an additional "short name" field, that will be used for saving the correct names (or I can actually use the existing BibTeX `shorthand` for that: @nitsnatsnok, what do you think?).

As for the empty entries, as I said already [here](https://github.com/lingdb/CoBL/issues/333#issuecomment-257550818) in #333, the list in fact consists of a single entry:
> there is only a single one on my local server (namely, the deprecated ID 57).

**Comment by nitsnatsnok** [comment]
Using the `shorthand` field for this is an excellent idea! Some of the entries (namely those with special short forms like “LIV²”) already have this field, for the rest just add it and fill it with the short form from the csv table I gave you.

If there's just a single empty entry, how come the sources list shows at least six of them? Please make the entries display their IDs, this will allow us to solve this. As for ID 57, this is indeed a deprecated source (see [here](https://github.com/lingdb/CoBL/issues/223#issuecomment-253739125)), but its data should have remained in the database for now and it is indeed displayed correctly with its title in the sources list. If you make all three counters work and show the citations I can begin cleaning up this and other deprecated sources, cf. #332.

**Comment by khoidt** [comment]
There is probably an error in line 111 of the `.csv` file. The whole line looks like this:
> c 1997 by Isidore Dyen, Joseph Kruskal, and Paul Black. Redistributable for academic, non-commercial purposes.
@nitsnatsnok, could you please check it?

**Comment by khoidt** [comment]
### Mistakes in short citations?
While adding the new data I've stumbled upon inconsequential format in the short citations, e.g.:

> Kordić 1997
> Neukom & Patnaik 2003

vs.

> H. J. Holm 2011
> G. Cardona & Jain 2003

@nitsnatsnok, would it be difficult to correct this? Otherwise, short citations with first initials will make sorting a true disaster.

**Comment by nitsnatsnok** [comment]
> error in line 111

fixed

> inconsequential format in the short citations

It's deceptive, this is necessary to distinguish possibly different authors with the same surname, e.g. “G. Cardona” and “George Cardona”. While this without any doubt is the same person here, the program distinguishes them because of the data: “Cardona, G.” and “Cardona, George”. As this is little work, I changed the short forms and did some other minor improvements: [lexicon_source.txt](https://github.com/lingdb/CoBL/files/570812/lexicon_source.txt). Sorting should be no problem with these short forms, if they are not distinct we can adapt them later as well.

**Comment by khoidt** [comment]
@nitsnatsnok thanks for the update! The following IDs are still missing the new data:

ID | short form | long form
---|---|---
35|-|+
191|-|+
139|-|+
362|-|-

It is not a parsing issue: I checked the .csv file and the listed IDs are just not there.

**Comment by nitsnatsnok** [comment]
All of those IDs are treated in #223 – if necessary, just make dummy entries with the information from there and **mark them as deprecated**.

**Comment by khoidt** [comment]
## Updates
The new version is now in `devel`. It has the following changes:

### Data:
- Added shorthand and citation text from `lexicon_source.csv` (`306_0129_import_source_citation_forms.py`)
- Deprecates sources with IDs 35, 191, 139, 362 (`306_0131_deprecate_sources.py`)

### Database:
- Source new fields:
 - `TRS` (s. #332)
 - `respect` (s. #332)
- Source behavior:
 - Sorted alphabetically according to shorthand (closes #333)
 - Previewed as shorthand by default in general and in citation forms

### Functionality:
- Adds TRS checkboxes column in `/sources/`.
- Adds missing and new fields to details and edit in `/sources/`.
- Adds Cogset counter in /sources/.
- Adds links to /source/(id)/cognacy/ in Cognacy column
- Adds links to /source/(id)/cogset/  in Cogset column
- Adds links to /source/(id)/lexeme/ in Lexeme column

### Views and URLs:
- Adds `/source/(id)/cognacy/` for displaying `CognateJudgementCitation `objects related to Source.
- Adds `/source/(id)/cogset/` for displaying `CognateClassCitation `related to Source.
- Adds `/source/(id)/lexeme/` for displaying `LexemeCitation `objects related to Source.

### Permissions:
- Allows editing, changing deprecated and `TRS` status and importing sources in `/sources/` for superusers only (_adding and editing sources is still partly possible for non-superusers in citation views_)

### Interface:
- Improves table layout in `/sources/`.
- Hides editing, changing deprecated status and importing options in `/sources/` from non-superusers.
- Added color marking for `TRS` status.
- Changed color scheme for sources table.

@runjak, deploy it, please, when you are available.

**Comment by runjak** [comment]
@khoidt I've deployed the current state of devel.

I've changed two things about your code:

1. One of the migrations didn't work because it tried to use a model structure that was no longer available. To circumvent this problem use `apps.get_model` as shown in e895bb9d9ebd23be4f156ed23037ae671249179d.
2. I've adjusted the code style to confirm with `flake8` as good as possible with commit 2e0cbe662144bd419cca7f373ffcc9b3bca0a971. Some things don't confirm currently because we're still on `python2.7`, but I think we should try to get close to this anyway to strife for a consistent style of code. If you agree with this it would be cool if you could check code with `flake8` or use `autopep8` before committing .)

Otherwise everything appears good from my point of view. The description certainly sounds like a good step forward :+1:

**Comment by nitsnatsnok** [comment]
The following tasks are still open here:
- [ ] replicate the standard CLLD system in terms of layout and function, see [this comment](https://github.com/lingdb/CoBL/issues/344#issuecomment-259112418)
- [ ] add a “Add Source” button with a mask to enter a new source to the list
- [ ] Embed bibliographical data in the webpages for Zotero etc. to pick up

**Comment by khoidt** [comment]
The problems addressed here are seem to be solved, so I'm taking the liberty to close this issue. For some more recent issues on the citation system see now #344. Branch #306 remains for now for comitting citation-related changes.
