### ISSUE TITLE
Fix Cancel button on cognate class citation form

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#372]
In cobl.info/cognate/_ID_/add-citation/, there is one button to submit the citation and one to cancel the action. However, when _Cancel_ is clicked, the page just shows the error “This field is required.” above the Source field rather than return to the cognate class view cobl.info/cognate/_ID_:
![2016-12-05-101843_1366x768_scrot](https://cloud.githubusercontent.com/assets/2664162/20879512/75200066-bad4-11e6-8cc4-1301276a15f3.png)
When a source is chosen, _Cancel_ does not cancel the action, but on the contrary adds the citation exactly like _Submit_ does, so it seems both buttons function equally.

**Comment by khoidt** [comment]
Solved with the last update. Please, close this after the deployment and testing of d4db9f2.

**Comment by runjak** [comment]
:rocket: deployed.

**Comment by nitsnatsnok** [comment]
Only partially solved: Cancelling works now, but still requires a source to be chosen first (with a much neater message though):
![2016-12-20-102832_1366x768_scrot](https://cloud.githubusercontent.com/assets/2664162/21345124/2d54e702-c69f-11e6-9949-2ba45558836f.png)

**Comment by khoidt** [comment]
Solved by 9f18519. Can be closed after deployment and testing.

**Comment by runjak** [comment]
Deployed.
