### ISSUE TITLE
Sources list unreachable

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#373]
I'm not able to reach the sources list http://cobl.info/sources/ any more, the website just gives me the “Page unavailable” error:

![2016-12-05-111024_1366x768_scrot](https://cloud.githubusercontent.com/assets/2664162/20881287/f387d2c4-badb-11e6-9022-d4366bcc7c58.png)

Interestingly, the top bar appears as if I'm not logged in, while in other tabs I remain logged in even after refreshing.

**Comment by khoidt** [comment]
I'm also getting this. Weird. It was working fine the whole time (last time I opened the page was on Saturday, I think). @runjak, could you check the logs, please?

**Comment by runjak** [comment]
There is indeed an exception in the logs. It looks like this:
```
[2016-12-05 13:09:22,833] ERROR Exception found by logExceptions.
Traceback (most recent call last):
  File "/CoBL/ielex/utilities.py", line 25, in f
    return func(*args, **kwargs)
  File "/CoBL/ielex/views.py", line 2031, in source_list
    "perms": source_perms_check(request.user),
  File "/CoBL/ielex/shortcuts.py", line 17, in render_template
    return render_to_response(template_path, context_instance=c)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 217, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/templatetags/django_tables2.py", line 155, in render
    return template.render(context.flatten())
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 56, in render
    result = self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 56, in render
    result = self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 224, in render
    nodelist.append(node.render(context))
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 56, in render
    result = self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 161, in render
    values = list(values)
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/rows.py", line 174, in items
    yield (column, self.get_cell(column.name))
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/rows.py", line 145, in get_cell
    return self._call_render(bound_column, value)
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/rows.py", line 156, in _call_render
    'table': self._table,
  File "/usr/local/lib/python2.7/dist-packages/django_tables2/utils.py", line 501, in call_with_appropriate
    return fn(**kwargs)
  File "/CoBL/ielex/tables.py", line 119, in render_details
    'id="%s">More</button>%s' % (record.pk, record.COinS)
  File "/CoBL/ielex/lexicon/models.py", line 430, in COinS
    % (rft_val_dict[self.ENTRYTYPE]))
KeyError: u''
```

**Comment by runjak** [comment]
I'll also provide you with a recent database dump, @khoidt - just because it may make sense because it makes reproduction easier and you should have it anyway.

**Comment by khoidt** [comment]
@runjak, thanks. This is due to sources with no type specified and was in fact already corrected a couple of days ago as the cause of #368. I will commit and push it in a couple of minutes.

**Comment by nitsnatsnok** [comment]
Highly plausible: I did add a source today and forgot to specify a type for it – great work you both! You keep in mind making this impossible, do you? `ENTRYTYPE` should be a mandatory field to add a source. To simplify entering correct information there, the field could use an example or even a list of valid types (we don't use many at the moment) next to it.

**Comment by runjak** [comment]
Alright, @khoidt - just @ mention me once the commit is ready - I'll then go ahead with deployment.

**Comment by khoidt** [comment]
For now `ENTRYTYPE` stays non-mandatory, as changing this in a rush is risky -- especially if there are still some sources with no type specified in the database. Please open an issue to correct this in the database first. After this is done it won't be a problem to make this a mandatory field.

**Comment by khoidt** [comment]
Fixed in the [last update](https://github.com/lingdb/CoBL/issues/344#issuecomment-264850822). Close when deployed and tested.

**Comment by nitsnatsnok** [comment]
It happens again! For #366 I changed the experts' ENTRYTYPE to `misc`, and now the error is back.

**Comment by khoidt** [comment]
@nitsnatsnok, the allowed values of `ENTRYTYPE` are the following:
book, article, journal, expert, online and inbook.
If there are other types, let me know, please, before adding them.

**Comment by nitsnatsnok** [comment]
@khoidt Oh, OK – for #366 we certainly could use `misc` then.

**Comment by khoidt** [comment]
OK, I changed the code in a way that allows generic types. This might (and definitely will) affect the `COinS` metadata output. To translate the types correctly I'll need a dictionary of BiBTeX -> COinS types (best to keep it in #366), like {'book': 'book', 'article': 'journal',} etc.

**Comment by khoidt** [comment]
## Update
- Allow generic `ENTRYTYPE` for `Source`.
---
@runjak, in #306.

**Comment by nitsnatsnok** [comment]
Works like a charm, thank you both for your patience!
